version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.1-alpine
    environment:
      - PGDATA=/data
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    logging:
      driver: 'json-file'
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
