# Generated by Django 3.1.5 on 2021-06-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User
import random
import string


def add_user_to_exiting_todos(apps, schema_editor):
    Task = apps.get_model("todos", "Task")
    letters = string.ascii_lowercase
    username = "".join(random.choice(letters) for i in range(10))
    user = User.objects.create_user(username, "foo@bar.com", "johnpassword")
    user.save()

    tasks = Task.objects.all()
    for task in tasks:
        task.user_id = user.id

    Task.objects.bulk_update(tasks, ["user_id"])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_user_to_exiting_todos, do_nothing),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
